anjaligupta0621/EasyConnect

backend/go.mod, backend/go.sum, backend/main.go, backend/public/index.html
Created main.go file
Created Get User Endpoint
=> [Issue #3][Milestone #1] Basic API to fetch the data.

backend/dbCreation.go, backend/endpoints.go, backend/main.go
Desgined GET request which authenticates login details.
Returns User details on successful login.
=> [Issue #11] Design Login Authentication API

backend/dbashHandler
API handlers for job posting on the dashboard.
The page will contain jobs posted. Selected, rejected. Progress of jobs. History. Recruiter's history, Commission, work, and multiple other stuff.
The same page might be used for Seeker's pages handled properly on the frontend accordingly.
=> Dashboard Main

.dockerignore, Dockerfile
Adding the docker support for smooth building process across different system.
=> [Sprint 2][Issue #26] Add Docker Build support

backend/endpoints.go, backend/main.go
Adding Cors permission for cross origin
=> [Sprint-2][Issue#31][CORS Permission]

package-lock.json, package.json, src/App.js, src/components/jobDetails.component.js, src/components/organizationDetails.component.js, src/components/postJob.component.js, src/css/bootstrap 2.css, src/css/bootstrap.css, src/css/bootstrap.min 2.css, src/css/bootstrap.min.css, src/css/toggle.css
- Created a PostJob (parent) Component mentioned in #24  which will allow a recruiter to post new jobs for hiring.
- Created two children components (jobDetails and organizationDetails) for implementing multi-step form functionality.
=> Post a Job Component

backend/endpoints.go
Changing HTTP response from string to JSON in case of failure.
Adding CORS setup.
=> [Sprint 2][Issue 33] Return JSON as respnse

src/components/login.component.js, src/components/navbar.component.js
ApI call enhancement and response Json handling.
=> [Sprint2][Issue#36][API call Enhancement]

backend/dbCreation.go, backend/jobEndpoints.go, backend/main.go
API added to add job from Recruiter's profile.
=> [Sprint 2][Added API to add Job]

src/components/jobDetails.component.js, src/components/login.component.js
- Backend Linked with PostJob Component (#46)
=> Backend added to PostJob

backend/main.go
=> [Sprint 2][Corrected URLs for Post APIs]

cypress/integration/uitesting/login_spec.js, cypress/integration/uitesting/logout_spec.js, cypress/integration/uitesting/postjob_spec.js
Adding LogIn, LogOut,Post Job Component testing using Cypress.
=> UI cypress testing changes

backend/handler/jobEndpoints.go, backend/jobEndpoints_test.go
Added unit tests for Job APIs
Corrected json response for GetJobs API
=> [Sprint 2][Issue 60] Added unit tests for Job APIs

src/components/header.component.js, src/components/jobDetails.component.js, src/components/login.component.js, src/components/postJobDashBoard.component.js
- The recruiter can now see the jobs posted by him/her (For #50)
=> Backend Linked For PostJobDashboard

src/components/login.component.js, src/components/postJobDashBoard.component.js
Linked backend for SignUp Component for Issue #68
=> Signup backend linked

src/components/jobDetails.component.js, src/components/postJobDashBoard.component.js
=> Minor improvement in postjobDashboard

backend/handler/endpoints.go
Return error is recruiter's email already in the database.
=> [Sprint 3][Handling duplicate entries]

backend/handler/jobEndpoints.go, backend/server/server.go
=> [Sprint 3][Adding API for Applicant's perspective]

public/index.html, src/components/Pagination.component.js, src/components/jobseeker.component.js, src/components/login.component.js, src/components/postJobDashBoard.component.js
- Displayed all the jobs to the job seeker (Issue #82 ). 
- Added Pagination so that a maximum of 10 jobs are visible per page.
=> Displayed All Jobs and Added Pagination

backend/handler/candidateEndpoints.go, backend/initDB/dbCreation.go, backend/models/models.go, backend/server/server.go, backend/utils/utils.go
Adding table model for Candidate.
Adding Login and Signup APIs for Candidate.
=> [Sprint 3][Issue 25][Designing model for Candidate Profile]

src/components/applyJobModal.component.js, src/components/jobseeker.component.js
- Added the apply jobs feature for a user to apply to his/her desired job. (Issue #85)
=> Apply Jobs Feature Added

backend/handler/endpoints.go, backend/server/server.go
Changes in cookies and auth modes
=> Login API Updates

backend/handler/candidateEndpoints.go, src/components/jobDetails.component.js, src/components/login.component.js, src/components/postJobDashBoard.component.js, src/components/userLoginModal.component.js
=> PostJob fixed

backend/go.mod, backend/go.sum, backend/handler/candidateEndpoints.go, backend/initDB/dbCreation.go, backend/models/models.go
Editing one to many relationship schema for jobs
Adding many to many relationship schema for candidates_jobs
=> [Sprint 3][Correcting relationships between tables]

backend/handler/candidateEndpoints.go
=> [Sprint 3][Quick Fix]

backend/handler/candidateEndpoints.go, backend/handler/endpoints.go, backend/handler/jobEndpoints.go, backend/models/models.go, backend/server/server.go
A candidate can apply to job
Recruiter can see how many candidates applied to jobs
=> [Sprint 3][Adding apply job API]

backend/candidateEndpoints_test.go, backend/endpoints_test.go, backend/jobEndpoints_test.go
Added new test cases for new APIs
=> [Sprint 3][Unit Tests for Backend]

src/components/home.component.js, src/components/jobDetails.component.js, src/components/jobseeker.component.js, src/components/postJobDashBoard.component.js, src/components/userLoginModal.component.js
- Candidates can apply to multiple jobs with a single click (Issue #85)
- Recruiter can view the number of applicants that applied to a particular job.
=> Apply Jobs Feature

backend/handler/jobEndpoints.go, backend/models/models.go
Updating candidates_jobs table for apply job API
=> [Sprint 4][Adding candidate and job relationship]

backend/handler/jobEndpoints.go, backend/models/models.go, backend/server/server.go
API to get candidates who applied to jobs posted by a recruiter with recruiter id as input.
API to get candidates who applied to jobs with job id as input.
=> [Sprint 4][API to get applied candidates]

backend/handler/jobEndpoints.go, backend/server/server.go
Get a list of applicants to a specific role.
Accepting json as input to API instead of uint.
=> [Sprint 4][API to get applicants to specific role]

src/components/jobDetails.component.js, src/components/jobseeker.component.js, src/components/postJobDashBoard.component.js, src/components/shortlistCandidate.component.js
Display the candidates who applied for the Job posted by that recruiter
=> Update the Job Details and Shortlisted Candidates

backend/go.mod, backend/go.sum, backend/handler/candidateEndpoints.go, backend/initDB/dbCreation.go, backend/models/models.go, backend/server/server.go
API for Candidate Profile Update.
=> [Sprint 4] #142 Candidate Profile API

src/components/Extras.js, src/components/Routes.component.js, src/components/viewCandidate.component.js
- JobSeekers can view their profile information. (#129 )
=> User/JobSeeker Profile

backend/handler/candidateEndpoints.go, backend/handler/endpoints.go, backend/server/server.go, backend/utils/utils.go
API for Candidate profile and minor changes in userAuth.
=> [Sprint 4] Candidate Profile API #157

src/components/header.component.js, src/components/jobSeekerHeader.component.js, src/components/jobseeker.component.js, src/components/viewCandidate.component.js
=> user profile linked to backend

src/components/viewCandidate.component.js
- User/Candidate will now be able to see their profile information using a different tab in the JobSeeker home section. (#129 )
=> User profile Completed

backend/candidateEndpoints_test.go, backend/endpoints_test.go, backend/handler/candidateEndpoints.go, backend/jobEndpoints_test.go
Unit test cases added for backend APIs
=> [Sprint 4][Unit tests for backend]

backend/candidateEndpoints_test.go, backend/endpoints_test.go, backend/handler/candidateEndpoints.go, backend/handler/endpoints.go, backend/handler/jobEndpoints.go, backend/jobEndpoints_test.go, backend/tests/candidate_test.go, backend/utils/utils.go
=> [Sprint 4] Backend Test case Updates
